"""create goodreads books table

Revision ID: 2758cc2497a7
Revises: 9918fe1463bc
Create Date: 2026-09-16 11:49:33.966515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2758cc2497a7'
down_revision: Union[str, Sequence[str], None] = '9918fe1463bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goodreads_books',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('author', sa.String(length=256), nullable=False),
    sa.Column('isbn', sa.String(length=32), nullable=True),
    sa.Column('isbn13', sa.String(length=32), nullable=True),
    sa.Column('my_rating', sa.Float(), nullable=True),
    sa.Column('bookshelves', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('date_read', sa.Date(), nullable=True),
    sa.Column('raw_row', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goodreads_books_author'), 'goodreads_books', ['author'], unique=False)
    op.create_index(op.f('ix_goodreads_books_isbn'), 'goodreads_books', ['isbn'], unique=False)
    op.create_index(op.f('ix_goodreads_books_isbn13'), 'goodreads_books', ['isbn13'], unique=False)
    op.create_index(op.f('ix_goodreads_books_title'), 'goodreads_books', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_goodreads_books_title'), table_name='goodreads_books')
    op.drop_index(op.f('ix_goodreads_books_isbn13'), table_name='goodreads_books')
    op.drop_index(op.f('ix_goodreads_books_isbn'), table_name='goodreads_books')
    op.drop_index(op.f('ix_goodreads_books_author'), table_name='goodreads_books')
    op.drop_table('goodreads_books')
    # ### end Alembic commands ###
